default_language_version:
  python: python3.12
  node: 22.5.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
        args: [--django]
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.1
    hooks:
      - id: typos
        args: []

  - repo: https://github.com/biomjs/pre-commit
    rev: ""
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.4.1"]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"

  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.28.0'  # Update me!
    hooks:
      # both pre-commit and pre-push supported
      # -   id: talisman-push
      - id: talisman-commit
        entry: cmd --githook pre-commit
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.3.2
    hooks:
      - id: djade
        args: [--target-version, "5.1"]
